#!/bin/sh
#
# Install + update project environment

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

$SCRIPT_DIR/clean
$SCRIPT_DIR/install

betty-cropper syncdb
betty-cropper migrate
betty-cropper create_token
