#!/bin/sh
#
# Install + update project environment

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

$SCRIPT_DIR/clean
$SCRIPT_DIR/install

docker-compose run web betty-cropper syncdb
docker-compose run web betty-cropper migrate
docker-compose run web betty-cropper create_token
