#!/bin/sh -e
# Publish package to PyPi
#
# Requires you setup a PyPi account and setup your ~/.pypirc config

# Make sure no local modifications
if ! git diff-index --quiet HEAD --; then
    echo "Error! Local directory has changes. Please revert, stash or commit!"
    exit 1
fi

scripts/lint
scripts/test

# mparent(2017-07-13): Use legacy upload API, Betty Cropper is deprecated and don't want to figure out new API (though
# might be simple).
python setup.py sdist upload -r https://upload.pypi.org/legacy/
