#!/bin/sh -euo pipefail
#
# Run local betty server

docker-compose run --service-ports web
#docker-compose run --service-ports web betty-cropper runserver 0.0.0.0:8080
#docker-compose up --force-recreate
